#!/bin/bash

if [[ $# -ne 1 ]]; then
   echo "usage: ${0} PID"
   exit 1
fi

TARGET_PID="${1}"

SCRIPT_DIR="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

"${SCRIPT_DIR}"/fd_watcher.py "${TARGET_PID}" \
|"${SCRIPT_DIR}"/fd_decoder.py \
|"${SCRIPT_DIR}"/fd_viewer.py